
try {
    console.log('normal');
    console.log(s);
} catch{
    console.log(err);
}